version: "3.8"

services:
  postgres_db:
    image: postgres
    container_name: sync360
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sync360
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.sync360:/var/lib/postgresql/data
